// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "../../../../../Program Files (x86)/Common Files/Microsoft Shared/MSEnv/PublicAssemblies/EnvDTE.dll"
#r "../../../../../Program Files (x86)/Common Files/Microsoft Shared/MSEnv/PublicAssemblies/EnvDTE80.dll"
#r "Microsoft.Build.Framework.dll"
#r "Microsoft.CSharp.dll"
#r "../../../../../Program Files (x86)/Microsoft Visual Studio 14.0/VSSDK/VisualStudioIntegration/Common/Assemblies/v4.0/Microsoft.VisualStudio.CoreUtility.dll"
#r "../../../../../Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Shell.12.0/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Shell.12.0.dll"
#r "../../../../../Program Files (x86)/Microsoft Visual Studio 14.0/VSSDK/VisualStudioIntegration/Common/Assemblies/v4.0/Microsoft.VisualStudio.Shell.Immutable.12.0.dll"
#r "../../../../../Program Files (x86)/Microsoft Visual Studio 14.0/VSSDK/VisualStudioIntegration/Common/Assemblies/v2.0/Microsoft.VisualStudio.Shell.Interop.dll"
#r "../../../../../Program Files (x86)/Microsoft Visual Studio 14.0/VSSDK/VisualStudioIntegration/Common/Assemblies/v4.0/Microsoft.VisualStudio.Text.Data.dll"
#r "../../../../../Program Files (x86)/Microsoft Visual Studio 14.0/VSSDK/VisualStudioIntegration/Common/Assemblies/v4.0/Microsoft.VisualStudio.Text.Logic.dll"
#r "../../../../../Program Files (x86)/Microsoft Visual Studio 14.0/VSSDK/VisualStudioIntegration/Common/Assemblies/v4.0/Microsoft.VisualStudio.Text.UI.dll"
#r "../../../../../Program Files (x86)/Microsoft Visual Studio 14.0/VSSDK/VisualStudioIntegration/Common/Assemblies/v4.0/Microsoft.VisualStudio.Text.UI.Wpf.dll"
#r "../../../../../Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualStudio.Threading/v4.0_12.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualStudio.Threading.dll"
#r "PresentationCore.dll"
#r "PresentationFramework.dll"
#r "System.ComponentModel.Composition.dll"
#r "System.Core.dll"
#r "System.Data.DataSetExtensions.dll"
#r "System.Data.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "System.Xaml.dll"
#r "System.Xml.dll"
#r "WindowsBase.dll"