// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "../../../../../Program Files (x86)/Common Files/Microsoft Shared/MSEnv/PublicAssemblies/EnvDTE.dll"
#r "../../../../../Program Files (x86)/Common Files/Microsoft Shared/MSEnv/PublicAssemblies/EnvDTE80.dll"
#r "../../packages/FsEye/lib/net40/plugins/FsEye.DataGridView.Plugin.dll"
#r "../../packages/FsEye/lib/net40/FsEye.dll"
#r "../../packages/FsEye/lib/net40/plugins/FsEye.PropertyGrid.Plugin.dll"
#r "../../packages/FsEye/lib/net40/plugins/FsEye.TreeView.Plugin.dll"
#r "../../packages/FSharp.Compiler.Tools.4.0.0.1/tools/FSharp.Build.dll"
#r "../../packages/FSharp.Compiler.Tools.4.0.0.1/tools/FSharp.Compiler.dll"
#r "../../packages/FSharp.Compiler.Tools.4.0.0.1/tools/FSharp.Compiler.Interactive.Settings.dll"
#r "../../packages/FSharp.Compiler.Tools.4.0.0.1/tools/FSharp.Compiler.Server.Shared.dll"
#r "../../packages/FSharp.Compiler.Service/lib/net45/FSharp.Compiler.Service.dll"
#r "../../packages/FSharp.Core.Fluent-4.0/lib/portable-net45+netcore45+wpa81+wp8+MonoAndroid1+MonoTouch1/FSharp.Core.Fluent-4.0.dll"
#r "Microsoft.Build.dll"
#r "Microsoft.Build.Engine.dll"
#r "Microsoft.Build.Framework.dll"
#r "Microsoft.CSharp.dll"
#r "../../packages/Microsoft.VisualStudio.CoreUtility.14.0.23205/lib/net45/Microsoft.VisualStudio.CoreUtility.dll"
#r "../../../../../Program Files (x86)/Microsoft Visual Studio 12.0/VSSDK/VisualStudioIntegration/Common/Assemblies/v4.0/Microsoft.VisualStudio.Shell.12.0.dll"
#r "../../../../../Program Files (x86)/Microsoft Visual Studio 12.0/VSSDK/VisualStudioIntegration/Common/Assemblies/v4.0/Microsoft.VisualStudio.Shell.Immutable.12.0.dll"
#r "../../../../../Program Files (x86)/Microsoft Visual Studio 14.0/VSSDK/VisualStudioIntegration/Common/Assemblies/v2.0/Microsoft.VisualStudio.Shell.Interop.dll"
#r "../../packages/Microsoft.VisualStudio.Text.Data.14.0.23205/lib/net45/Microsoft.VisualStudio.Text.Data.dll"
#r "../../packages/Microsoft.VisualStudio.Text.Logic.14.0.23205/lib/net45/Microsoft.VisualStudio.Text.Logic.dll"
#r "../../packages/Microsoft.VisualStudio.Text.UI.14.0.23205/lib/net45/Microsoft.VisualStudio.Text.UI.dll"
#r "../../packages/Microsoft.VisualStudio.Text.UI.Wpf.14.0.23205/lib/net45/Microsoft.VisualStudio.Text.UI.Wpf.dll"
#r "../../../../../Program Files (x86)/Microsoft Visual Studio 12.0/VSSDK/VisualStudioIntegration/Common/Assemblies/v4.0/Microsoft.VisualStudio.Threading.dll"
#r "PresentationCore.dll"
#r "PresentationFramework.dll"
#r "System.ComponentModel.Composition.dll"
#r "System.Core.dll"
#r "System.Data.DataSetExtensions.dll"
#r "System.Data.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "System.Xaml.dll"
#r "System.Xml.dll"
#r "WindowsBase.dll"